[LUM-409] Implement Cosmos v0.46.0
lum-network/chain pull request #14
Opened 2022-10-25 10:07 UTC by Segfaultd

2022-10-26 14:08 UTC, lebascou reviewed
Implementation LGTM, we need to thoroughly test the following now:
- Keplr: RPC behaviour since it's been heavily deprecated and edited
- IBC: All features in a production like environment

2022-10-26 14:08 UTC, lebascou commented on x/dfract/client/cli/proposal.go
> +	govv1betatypes "github.com/cosmos/cosmos-sdk/x/gov/types/v1beta1"
I believe this should be `govtypesv1beta1` for consistency purpose.

2022-11-02 11:56 UTC, Segfaultd commented on app/app.go
> +		app.Logger().Info("v1.3.0 upgrade applied")
Well technically everything is running in that lambda.

2022-11-02 11:57 UTC, Segfaultd commented on app/keepers.go
> +		app.IBCKeeper.ChannelKeeper, // may be replaced with IBC middleware
May be replaced in the future if we require an IBC fee middleware.

2022-11-07 15:47 UTC, lebascou requested changes

2022-11-07 15:47 UTC, lebascou commented on app/app.go
> -}
Looks like a missing bracket 💡

2022-11-07 16:19 UTC, lebascou approved these changes

2022-11-07 16:21 UTC, merged